# Generated by Django 3.2.7 on 2021-09-17 22:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photographer_name', models.CharField(max_length=100)),
                ('photographer_location', models.CharField(max_length=100)),
                ('photographer_instagram_hadnle', models.CharField(blank=True, max_length=500)),
                ('insta_followers', models.CharField(blank=True, max_length=100)),
                ('mutual_models', models.CharField(blank=True, max_length=1000)),
                ('outreach', models.CharField(blank=True, max_length=5)),
                ('outreach_date', models.DateField(blank=True)),
                ('agencies_work_with', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000), size=None)),
                ('notes', models.CharField(blank=True, max_length=5000)),
            ],
        ),
    ]
