# Generated by Django 3.2.7 on 2021-09-17 22:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography_list_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='agencies_work_with',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000), blank=True, size=None),
        ),
    ]
