# Generated by Django 3.2.7 on 2021-09-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography_list_tracking', '0002_alter_photographer_agencies_work_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='agencies_work_with',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
