# Generated by Django 3.2.7 on 2021-09-18 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography_list_tracking', '0003_alter_photographer_agencies_work_with'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photographer',
            old_name='photographer_instagram_hadnle',
            new_name='photographer_instagram_handle',
        ),
    ]
