# Generated by Django 3.2.7 on 2021-09-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography_list_tracking', '0004_rename_photographer_instagram_hadnle_photographer_photographer_instagram_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='outreach',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
