# Generated by Django 3.2.7 on 2021-09-18 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photography_list_tracking', '0005_alter_photographer_outreach'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photography_list_track', to=settings.AUTH_USER_MODEL),
        ),
    ]
