# Generated by Django 3.2.7 on 2021-09-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('insta_followers', models.CharField(blank=True, max_length=100)),
                ('digitals_required', models.CharField(blank=True, max_length=5)),
                ('digitals_requirements', models.CharField(blank=True, max_length=2000)),
                ('outreach', models.CharField(blank=True, max_length=5)),
                ('date_digitals_submitted', models.DateField(auto_now=True)),
                ('notes', models.CharField(blank=True, max_length=5000)),
            ],
        ),
    ]
