# Generated by Django 3.2.7 on 2021-09-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_tracking', '0002_rename_lead_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='date_digitals_submitted',
            field=models.DateField(blank=True),
        ),
    ]
