# Generated by Django 3.2.7 on 2021-09-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_tracking', '0003_alter_agency_date_digitals_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='agency_instagram_hadnle',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
