# Generated by Django 3.2.7 on 2021-09-18 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency_tracking', '0004_agency_agency_instagram_hadnle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='agency_instagram_hadnle',
            new_name='agency_instagram_handle',
        ),
    ]
