# Generated by Django 3.2.7 on 2021-09-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_tracking', '0005_rename_agency_instagram_hadnle_agency_agency_instagram_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='digitals_required',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agency',
            name='outreach',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
